### PR TITLE
fix: Fixed issues due to deprecated @hapi/joi package

### LINKED ISSUE #29: Update to latest version of koa-joi-router
The `@hapi/joi` package was deprecated in favor of `joi`. The `koa-joi-router` package has updated to this in version `7.0.0`, but this project remains out of date. My project was hitting an error by not installing `@hapi/joi`, and I believe it's related to this issue.

Regardless of this being the cause of my issue or not, I believe this project should update to the current version of `koa-joi-router`.

### PR DESCRIPTION
**Pull request by TheBeege**
Switched to using joi-to-swagger instead of o2team-joi-to-swagger, since o2team-joi-to-swagger is outdated.
Updated koa-joi-router to ^7.0.0 from ^6.0.0.

Closes #29

### CODE REVIEW

**Comment by TheBeege** [comment]
@chuyik Please check and merge. My project depends on this. Tests pass.

**Comment by chuyik** [comment]
I will find time to merge upstream to `o2team-joi-to-swagger`, since it does not support `Joi.lazy`, and missing logic on `Joi.any`.

**Comment by TheBeege** [comment]
@chuyik Why are you using a fork of that project when it appears it's maintained well? Is it missing something? I can get a pull request setup for it.

**Comment by chuyik** [comment]
I just said it does not support Joi.lazy, and missing logic on Joi.any.
But Joi changed its API so frequently, I don't know if the fixes I wrote in 2017 is working anymore.

**Comment by TheBeege** [comment]
Ah, apologies. Is there anything I can do to help?

**Pull request closed without merging**
